/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Technology
    /// </summary>
    [DataContract]
    public partial class Technology :  IEquatable<Technology>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Technology" /> class.
        /// </summary>
        /// <param name="TechnologyId">TechnologyId.</param>
        /// <param name="TechnologyName">TechnologyName.</param>
        public Technology(int? TechnologyId = default(int?), string TechnologyName = default(string))
        {
            this.TechnologyId = TechnologyId;
            this.TechnologyName = TechnologyName;
        }
        
        /// <summary>
        /// Gets or Sets TechnologyId
        /// </summary>
        [DataMember(Name="TechnologyId", EmitDefaultValue=false)]
        public int? TechnologyId { get; set; }

        /// <summary>
        /// Gets or Sets TechnologyName
        /// </summary>
        [DataMember(Name="TechnologyName", EmitDefaultValue=false)]
        public string TechnologyName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Technology {\n");
            sb.Append("  TechnologyId: ").Append(TechnologyId).Append("\n");
            sb.Append("  TechnologyName: ").Append(TechnologyName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Technology);
        }

        /// <summary>
        /// Returns true if Technology instances are equal
        /// </summary>
        /// <param name="other">Instance of Technology to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Technology other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.TechnologyId == other.TechnologyId ||
                    this.TechnologyId != null &&
                    this.TechnologyId.Equals(other.TechnologyId)
                ) && 
                (
                    this.TechnologyName == other.TechnologyName ||
                    this.TechnologyName != null &&
                    this.TechnologyName.Equals(other.TechnologyName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.TechnologyId != null)
                    hash = hash * 59 + this.TechnologyId.GetHashCode();
                if (this.TechnologyName != null)
                    hash = hash * 59 + this.TechnologyName.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
