/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// UpdateMultipleStatuses
    /// </summary>
    [DataContract]
    public partial class UpdateMultipleStatuses :  IEquatable<UpdateMultipleStatuses>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateMultipleStatuses" /> class.
        /// </summary>
        /// <param name="Status">Status.</param>
        /// <param name="TicketUUID">TicketUUID.</param>
        public UpdateMultipleStatuses(string Status = default(string), List<string> TicketUUID = default(List<string>))
        {
            this.Status = Status;
            this.TicketUUID = TicketUUID;
        }
        
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="Status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets TicketUUID
        /// </summary>
        [DataMember(Name="TicketUUID", EmitDefaultValue=false)]
        public List<string> TicketUUID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateMultipleStatuses {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TicketUUID: ").Append(TicketUUID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as UpdateMultipleStatuses);
        }

        /// <summary>
        /// Returns true if UpdateMultipleStatuses instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateMultipleStatuses to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateMultipleStatuses other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                ) && 
                (
                    this.TicketUUID == other.TicketUUID ||
                    this.TicketUUID != null &&
                    this.TicketUUID.SequenceEqual(other.TicketUUID)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                if (this.TicketUUID != null)
                    hash = hash * 59 + this.TicketUUID.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
