/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Attachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AttachmentTests
    {
        // TODO uncomment below to declare an instance variable for Attachment
        //private Attachment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Attachment
            //instance = new Attachment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Attachment
        /// </summary>
        [Test]
        public void AttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Attachment
            //Assert.IsInstanceOfType<Attachment> (instance, "variable 'instance' is a Attachment");
        }

        /// <summary>
        /// Test the property 'FILE_NAME'
        /// </summary>
        [Test]
        public void FILE_NAMETest()
        {
            // TODO unit test for the property 'FILE_NAME'
        }
        /// <summary>
        /// Test the property 'FILE_EXTENSION'
        /// </summary>
        [Test]
        public void FILE_EXTENSIONTest()
        {
            // TODO unit test for the property 'FILE_EXTENSION'
        }
        /// <summary>
        /// Test the property 'FILE'
        /// </summary>
        [Test]
        public void FILETest()
        {
            // TODO unit test for the property 'FILE'
        }
        /// <summary>
        /// Test the property 'TICKET_ATTACHMENT_UUID'
        /// </summary>
        [Test]
        public void TICKET_ATTACHMENT_UUIDTest()
        {
            // TODO unit test for the property 'TICKET_ATTACHMENT_UUID'
        }
        /// <summary>
        /// Test the property 'COMPANY_ID'
        /// </summary>
        [Test]
        public void COMPANY_IDTest()
        {
            // TODO unit test for the property 'COMPANY_ID'
        }

    }

}
