/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Reminder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReminderTests
    {
        // TODO uncomment below to declare an instance variable for Reminder
        //private Reminder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Reminder
            //instance = new Reminder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Reminder
        /// </summary>
        [Test]
        public void ReminderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Reminder
            //Assert.IsInstanceOfType<Reminder> (instance, "variable 'instance' is a Reminder");
        }

        /// <summary>
        /// Test the property 'TICKET_REMINDER_ID'
        /// </summary>
        [Test]
        public void TICKET_REMINDER_IDTest()
        {
            // TODO unit test for the property 'TICKET_REMINDER_ID'
        }
        /// <summary>
        /// Test the property 'TICKET_ID'
        /// </summary>
        [Test]
        public void TICKET_IDTest()
        {
            // TODO unit test for the property 'TICKET_ID'
        }
        /// <summary>
        /// Test the property 'INTERVAL'
        /// </summary>
        [Test]
        public void INTERVALTest()
        {
            // TODO unit test for the property 'INTERVAL'
        }
        /// <summary>
        /// Test the property 'RECURRENCE'
        /// </summary>
        [Test]
        public void RECURRENCETest()
        {
            // TODO unit test for the property 'RECURRENCE'
        }
        /// <summary>
        /// Test the property 'TYPE'
        /// </summary>
        [Test]
        public void TYPETest()
        {
            // TODO unit test for the property 'TYPE'
        }
        /// <summary>
        /// Test the property 'DATE_CREATED'
        /// </summary>
        [Test]
        public void DATE_CREATEDTest()
        {
            // TODO unit test for the property 'DATE_CREATED'
        }

    }

}
