/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Server
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServerTests
    {
        // TODO uncomment below to declare an instance variable for Server
        //private Server instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Server
            //instance = new Server();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Server
        /// </summary>
        [Test]
        public void ServerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Server
            //Assert.IsInstanceOfType<Server> (instance, "variable 'instance' is a Server");
        }

        /// <summary>
        /// Test the property 'ServerId'
        /// </summary>
        [Test]
        public void ServerIdTest()
        {
            // TODO unit test for the property 'ServerId'
        }
        /// <summary>
        /// Test the property 'DisplayServerName'
        /// </summary>
        [Test]
        public void DisplayServerNameTest()
        {
            // TODO unit test for the property 'DisplayServerName'
        }

    }

}
