/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Technology
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TechnologyTests
    {
        // TODO uncomment below to declare an instance variable for Technology
        //private Technology instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Technology
            //instance = new Technology();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Technology
        /// </summary>
        [Test]
        public void TechnologyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Technology
            //Assert.IsInstanceOfType<Technology> (instance, "variable 'instance' is a Technology");
        }

        /// <summary>
        /// Test the property 'TechnologyId'
        /// </summary>
        [Test]
        public void TechnologyIdTest()
        {
            // TODO unit test for the property 'TechnologyId'
        }
        /// <summary>
        /// Test the property 'TechnologyName'
        /// </summary>
        [Test]
        public void TechnologyNameTest()
        {
            // TODO unit test for the property 'TechnologyName'
        }

    }

}
