/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TicketPremadeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TicketPremadeResponseTests
    {
        // TODO uncomment below to declare an instance variable for TicketPremadeResponse
        //private TicketPremadeResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TicketPremadeResponse
            //instance = new TicketPremadeResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TicketPremadeResponse
        /// </summary>
        [Test]
        public void TicketPremadeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TicketPremadeResponse
            //Assert.IsInstanceOfType<TicketPremadeResponse> (instance, "variable 'instance' is a TicketPremadeResponse");
        }

        /// <summary>
        /// Test the property 'TICKET_PREMADE_RESPONSE_ID'
        /// </summary>
        [Test]
        public void TICKET_PREMADE_RESPONSE_IDTest()
        {
            // TODO unit test for the property 'TICKET_PREMADE_RESPONSE_ID'
        }
        /// <summary>
        /// Test the property 'BODY'
        /// </summary>
        [Test]
        public void BODYTest()
        {
            // TODO unit test for the property 'BODY'
        }
        /// <summary>
        /// Test the property 'TITLE'
        /// </summary>
        [Test]
        public void TITLETest()
        {
            // TODO unit test for the property 'TITLE'
        }
        /// <summary>
        /// Test the property 'COMPANY_ID'
        /// </summary>
        [Test]
        public void COMPANY_IDTest()
        {
            // TODO unit test for the property 'COMPANY_ID'
        }
        /// <summary>
        /// Test the property 'USER_ID'
        /// </summary>
        [Test]
        public void USER_IDTest()
        {
            // TODO unit test for the property 'USER_ID'
        }

    }

}
