/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Ticket
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TicketTests
    {
        // TODO uncomment below to declare an instance variable for Ticket
        //private Ticket instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Ticket
            //instance = new Ticket();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Ticket
        /// </summary>
        [Test]
        public void TicketInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Ticket
            //Assert.IsInstanceOfType<Ticket> (instance, "variable 'instance' is a Ticket");
        }

        /// <summary>
        /// Test the property 'TICKET_ID'
        /// </summary>
        [Test]
        public void TICKET_IDTest()
        {
            // TODO unit test for the property 'TICKET_ID'
        }
        /// <summary>
        /// Test the property 'SUBJECT'
        /// </summary>
        [Test]
        public void SUBJECTTest()
        {
            // TODO unit test for the property 'SUBJECT'
        }
        /// <summary>
        /// Test the property 'DATE_REQUIRED_BY'
        /// </summary>
        [Test]
        public void DATE_REQUIRED_BYTest()
        {
            // TODO unit test for the property 'DATE_REQUIRED_BY'
        }
        /// <summary>
        /// Test the property 'SEVERITY'
        /// </summary>
        [Test]
        public void SEVERITYTest()
        {
            // TODO unit test for the property 'SEVERITY'
        }
        /// <summary>
        /// Test the property 'DATE_CREATED'
        /// </summary>
        [Test]
        public void DATE_CREATEDTest()
        {
            // TODO unit test for the property 'DATE_CREATED'
        }
        /// <summary>
        /// Test the property 'SOURCE'
        /// </summary>
        [Test]
        public void SOURCETest()
        {
            // TODO unit test for the property 'SOURCE'
        }
        /// <summary>
        /// Test the property 'TICKET_UUID'
        /// </summary>
        [Test]
        public void TICKET_UUIDTest()
        {
            // TODO unit test for the property 'TICKET_UUID'
        }
        /// <summary>
        /// Test the property 'STATUS'
        /// </summary>
        [Test]
        public void STATUSTest()
        {
            // TODO unit test for the property 'STATUS'
        }
        /// <summary>
        /// Test the property 'IS_INTERNAL'
        /// </summary>
        [Test]
        public void IS_INTERNALTest()
        {
            // TODO unit test for the property 'IS_INTERNAL'
        }
        /// <summary>
        /// Test the property 'REQUESTOR_GROUP_USER_ID'
        /// </summary>
        [Test]
        public void REQUESTOR_GROUP_USER_IDTest()
        {
            // TODO unit test for the property 'REQUESTOR_GROUP_USER_ID'
        }
        /// <summary>
        /// Test the property 'ASSIGNEE_GROUP_USER_ID'
        /// </summary>
        [Test]
        public void ASSIGNEE_GROUP_USER_IDTest()
        {
            // TODO unit test for the property 'ASSIGNEE_GROUP_USER_ID'
        }
        /// <summary>
        /// Test the property 'OWNER_GROUP_USER_ID'
        /// </summary>
        [Test]
        public void OWNER_GROUP_USER_IDTest()
        {
            // TODO unit test for the property 'OWNER_GROUP_USER_ID'
        }
        /// <summary>
        /// Test the property 'REQUESTOR_NAME'
        /// </summary>
        [Test]
        public void REQUESTOR_NAMETest()
        {
            // TODO unit test for the property 'REQUESTOR_NAME'
        }
        /// <summary>
        /// Test the property 'OWNER_NAME'
        /// </summary>
        [Test]
        public void OWNER_NAMETest()
        {
            // TODO unit test for the property 'OWNER_NAME'
        }
        /// <summary>
        /// Test the property 'ASSIGNEE_NAME'
        /// </summary>
        [Test]
        public void ASSIGNEE_NAMETest()
        {
            // TODO unit test for the property 'ASSIGNEE_NAME'
        }
        /// <summary>
        /// Test the property 'OWNER_ACCOUNT_NAME'
        /// </summary>
        [Test]
        public void OWNER_ACCOUNT_NAMETest()
        {
            // TODO unit test for the property 'OWNER_ACCOUNT_NAME'
        }
        /// <summary>
        /// Test the property 'TICKET_MESSAGES'
        /// </summary>
        [Test]
        public void TICKET_MESSAGESTest()
        {
            // TODO unit test for the property 'TICKET_MESSAGES'
        }

    }

}
