/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TicketMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TicketMessageTests
    {
        // TODO uncomment below to declare an instance variable for TicketMessage
        //private TicketMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TicketMessage
            //instance = new TicketMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TicketMessage
        /// </summary>
        [Test]
        public void TicketMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TicketMessage
            //Assert.IsInstanceOfType<TicketMessage> (instance, "variable 'instance' is a TicketMessage");
        }

        /// <summary>
        /// Test the property 'TICKET_MESSAGE_ID'
        /// </summary>
        [Test]
        public void TICKET_MESSAGE_IDTest()
        {
            // TODO unit test for the property 'TICKET_MESSAGE_ID'
        }
        /// <summary>
        /// Test the property 'TICKET_ID'
        /// </summary>
        [Test]
        public void TICKET_IDTest()
        {
            // TODO unit test for the property 'TICKET_ID'
        }
        /// <summary>
        /// Test the property 'BODY'
        /// </summary>
        [Test]
        public void BODYTest()
        {
            // TODO unit test for the property 'BODY'
        }
        /// <summary>
        /// Test the property 'USER_ID'
        /// </summary>
        [Test]
        public void USER_IDTest()
        {
            // TODO unit test for the property 'USER_ID'
        }
        /// <summary>
        /// Test the property 'DATE_CREATED'
        /// </summary>
        [Test]
        public void DATE_CREATEDTest()
        {
            // TODO unit test for the property 'DATE_CREATED'
        }
        /// <summary>
        /// Test the property 'COMPANY_ID'
        /// </summary>
        [Test]
        public void COMPANY_IDTest()
        {
            // TODO unit test for the property 'COMPANY_ID'
        }
        /// <summary>
        /// Test the property 'TICKET_ATTACHMENTS'
        /// </summary>
        [Test]
        public void TICKET_ATTACHMENTSTest()
        {
            // TODO unit test for the property 'TICKET_ATTACHMENTS'
        }
        /// <summary>
        /// Test the property 'Element1'
        /// </summary>
        [Test]
        public void Element1Test()
        {
            // TODO unit test for the property 'Element1'
        }

    }

}
