/* 
 * ngDesk_Operations
 *
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UpdateMultipleStatuses
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateMultipleStatusesTests
    {
        // TODO uncomment below to declare an instance variable for UpdateMultipleStatuses
        //private UpdateMultipleStatuses instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateMultipleStatuses
            //instance = new UpdateMultipleStatuses();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateMultipleStatuses
        /// </summary>
        [Test]
        public void UpdateMultipleStatusesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateMultipleStatuses
            //Assert.IsInstanceOfType<UpdateMultipleStatuses> (instance, "variable 'instance' is a UpdateMultipleStatuses");
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TicketUUID'
        /// </summary>
        [Test]
        public void TicketUUIDTest()
        {
            // TODO unit test for the property 'TicketUUID'
        }

    }

}
